# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orbit < Formula
  desc "Unified CLI for monitoring services across cloud platforms"
  homepage "https://github.com/humanetools/orbit"
  version "0.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.6/orbit_0.2.6_darwin_amd64.tar.gz"
      sha256 "25b564ba4376098045cd41e68239f34444bca1be9ce5e2896650c9701eabaa17"

      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.6/orbit_0.2.6_darwin_arm64.tar.gz"
      sha256 "83e5801e3fe353b67e55abe7650ada8a88d28272b63b1cee1f73d6ef365ad2a8"

      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.6/orbit_0.2.6_linux_amd64.tar.gz"
      sha256 "19f7ffe2ff3ef1e46a505f131eb7649d839a66e761f3d2b0cdcf557ab3057181"
      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.6/orbit_0.2.6_linux_arm64.tar.gz"
      sha256 "45e23196d20e0bf6f6b040aa8bdaf987b005db36ae80dcec58ba31f7a0dc61ce"
      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  test do
    system "#{bin}/orbit", "--version"
  end
end
