# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orbit < Formula
  desc "Unified CLI for monitoring services across cloud platforms"
  homepage "https://github.com/humanetools/orbit"
  version "0.2.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.7/orbit_0.2.7_darwin_amd64.tar.gz"
      sha256 "edd9f40303915378e22ab5d027215f26ce9451f7d88b70dfbc20654b2d790a5e"

      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.7/orbit_0.2.7_darwin_arm64.tar.gz"
      sha256 "f61501d023bca179e8a10f34b190c18481ef904471f933242e2fdd0b38791ed5"

      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.7/orbit_0.2.7_linux_amd64.tar.gz"
      sha256 "d9485cd65db76c9d194af75258455d8ebb8b29b4eed64730c8e0249c675d16e4"
      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanetools/orbit/releases/download/v0.2.7/orbit_0.2.7_linux_arm64.tar.gz"
      sha256 "015bc940c9ee5c497eea41b8d546f973d1f5eaea68696ff44f19fdb1f53e3852"
      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  test do
    system "#{bin}/orbit", "--version"
  end
end
