# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orbit < Formula
  desc "Unified CLI for monitoring services across cloud platforms"
  homepage "https://github.com/humanetools/orbit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanetools/orbit/releases/download/v0.1.0/orbit_0.1.0_darwin_amd64.tar.gz"
      sha256 "be0aa2fbf4bb7b1ce468fd9923f99698ddfd12e378416b5bfcb0d7296fd975cf"

      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanetools/orbit/releases/download/v0.1.0/orbit_0.1.0_darwin_arm64.tar.gz"
      sha256 "7fd878c10794b3edadf9cd65106dcd8196207517b5d2764e9e5b0ccdf3b5a29b"

      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanetools/orbit/releases/download/v0.1.0/orbit_0.1.0_linux_amd64.tar.gz"
      sha256 "958fb97f29da66c82ab7bdd97d732654c6e2832764e1b00a3bb9fcedac352aa2"
      define_method(:install) do
        bin.install "orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanetools/orbit/releases/download/v0.1.0/orbit_0.1.0_linux_arm64.tar.gz"
      sha256 "e69e72457fed2985452d2cf00abc658297046e3e4a6495e75005c8c809f4f756"
      define_method(:install) do
        bin.install "orbit"
      end
    end
  end

  test do
    system "#{bin}/orbit", "--version"
  end
end
